version: 0.2
# Defining default values for all jobs
defaults: &defaults
phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      #- npm install sfdx-cli --global
  build:
    commands:
      - echo Build started on `14/05/2020`
      - echo $salesforceSITInstanceURL
      - echo $salesforceSITUserName
      - echo $salesforceSITClientId
      #- sfdx force:auth:jwt:grant --clientid 3MVG97quAmFZJfVyq3tLvSSXPZetZl3qbVbXU9EanjeRiVjbfUuab7ULGYnFCgt1Shpu37vRZ9sA5KwshFfhK --jwtkeyfile ./buildfiles/server.key --username balajibondar@gmail.com.CICD --instanceurl https://login.salesforce.com/ -a SIT
      - sfdx force:auth:jwt:grant --clientid 3MVG97quAmFZJfVyq3tLvSSXPZetZl3qbVbXU9EanjeRiVjbfUuab7ULGYnFCgt1Shpu37vRZ9sA5KwshFfhK --jwtkeyfile ./buildfiles/server.key --username balajibondar@gmail.com.CICD --instanceurl https://login.salesforce.com/ -a SIT
      #- sfdx force:mdapi:deploy -l RunLocalTests -c -d ./force-app/main/default/ -u SIT -w 10
      
