version: 0.2
# Defining default values for all jobs
defaults: &defaults
phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      #- npm install sfdx-cli --global
  build:
    commands:
      - echo Build started on ...
      #- echo $salesforceSITInstanceURL
      #- echo $salesforceSITUserName
      #- echo $salesforceSITClientId
      #- sfdx --help
      - sfdx force:doc:commands:list
      #- sfdx force:auth:jwt:grant --clientid 3MVG97quAmFZJfVyq3tLvSSXPZVmzNk9.oE45U60WYJmJ0wOXdimoJ5R5oVcCaTpjS0RQHIc5ZQugrN1ptkqq --jwtkeyfile ./buildfiles/server.key --username balajibondar@gmail.com.CICD --instanceurl https://login.salesforce.com/ -a SIT
      - sfdx force:auth:jwt:grant --clientid 3MVG97quAmFZJfVyq3tLvSSXPZVmzNk9.oE45U60WYJmJ0wOXdimoJ5R5oVcCaTpjS0RQHIc5ZQugrN1ptkqq--jwtkeyfile ./buildfiles/server.key --username balajibondar@gmail.com.CICD --instanceurl https://login.salesforce.com/ -a SIT
      #- sfdx force:mdapi:deploy -l RunLocalTests -c -d ./force-app/main/default/ -u SIT -w 10
      
